### ISSUE TITLE
boost::asio::ip::tcp 'native' method replaced with 'native_handle'

### ISSUE THREAD

**Issue by bmoss6** [mixmodeai/bro_tcplog_plugin#3]
When installing plugin with boost 1.6.7 compiling broke with error: boost::asio::ip::tcp has no method 'native'. According to https://github.com/kenba/via-httplib/issues/3, the native method was replaced with native_handle(). So, lines 120-122 in src/TcpSession.h
`		setsockopt(socket_.native(), SOL_SOCKET, SO_RCVTIMEO,  &tv, sizeof(tv));
		setsockopt(socket_.native(), SOL_SOCKET, SO_SNDTIMEO,  &tv, sizeof(tv));
		setsockopt(socket_.native(), SOL_SOCKET, SO_KEEPALIVE, &tv, sizeof(tv));` 
should be 
`		setsockopt(socket_.native_handle(), SOL_SOCKET, SO_RCVTIMEO,  &tv, sizeof(tv));
		setsockopt(socket_.native_handle(), SOL_SOCKET, SO_SNDTIMEO,  &tv, sizeof(tv));
		setsockopt(socket_.native_handle(), SOL_SOCKET, SO_KEEPALIVE, &tv, sizeof(tv));`
Making the change solved the problem for me.

**Comment by PSChrisHinshaw** [comment]
Thanks for reporting this.  The master branch has been updated with this change.
